language: android

jdk:
  - oraclejdk8

addons:
  apt:
    update: true

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - GOOGLE_PUBLISH_JSON=app/misc/android-publisher-account.json

android:
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-28.0.3
    - android-28

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_install:
  - sudo apt-get install -y gnupg2
  - gpg --batch --decrypt --output ${GOOGLE_PUBLISH_JSON} --passphrase ${GOOGLE_ACCOUNT_DECRYPTION_KEY} ${GOOGLE_PUBLISH_JSON}.gpg

script:
  - "./gradlew --info assembleRelease"

deploy:
  - provider: releases
    api_key: "${GITHUB_PUBLISH_OAUTH_TOKEN}"
    file: app/build/build/outputs/apk/release/app-release.apk
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    on:
      tags: true